flyway.url=jdbc:postgresql://postgres:5432/postgres
flyway.user=postgres
flyway.password=postgres
flyway.schemas=public
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true