server {
    listen 80;

    client_max_body_size 100m;

    # фронт
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # апи
    location /api/ {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # S3 — проксируем rustfs чтобы браузер мог открыть presigned URL
    location /s3/ {
        proxy_pass http://rustfs:9000/;
        proxy_set_header Host rustfs:9000;
    }
}